
name: snapshot

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
        server-id: sonatype-nexus-snapshots
        server-username: CI_DEPLOY_USERNAME
        server-password: CI_DEPLOY_PASSWORD
    - name: Deploy snapshot with Maven
      env:
        CI_DEPLOY_USERNAME: ${{ secrets.DEPLOY_USER }}
        CI_DEPLOY_PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
      run: mvn -s ci/settings.xml clean deploy -Dmaven.test.skip=true -Dinvoker.skip=true
